"""Rename Product.title to Product.name

Revision ID: 173541aefe9e
Revises: ddb7d0b8357b
Create Date: 2025-11-14 12:04:28.696551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '173541aefe9e'
down_revision: Union[str, Sequence[str], None] = 'ddb7d0b8357b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.Text(), nullable=False))
    op.alter_column('products', 'title', new_column_name='name')
    # op.add_column('products', sa.Column('name', sa.String(length=255), nullable=False))
    # op.drop_column('products', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'name', new_column_name='title')
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
