"""make username and account_id nullable, rename refresh_token

Revision ID: ddb7d0b8357b
Revises: 152c987d50e9
Create Date: 2025-11-10 14:36:59.003501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb7d0b8357b'
down_revision: Union[str, Sequence[str], None] = '152c987d50e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('refresh_token_hash', sa.String(length=255), nullable=False))
    op.drop_column('sessions', 'refresh_token')
    op.alter_column('users', 'account_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'account_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('sessions', sa.Column('refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('sessions', 'refresh_token_hash')
    # ### end Alembic commands ###
